/home/bhaskar/.eclipse/org.eclipse.platform_155965261_linux_gtk_x86/configuration/org.eclipse.osgi/276/0/.cp/images/alphab_sort_co.gif
/home/bhaskar/.eclipse/org.eclipse.platform_155965261_linux_gtk_x86/configuration/org.eclipse.osgi/289/0/.cp/icons/dtool16/alphab_sort_co.gif
/home/bhaskar/.eclipse/org.eclipse.platform_155965261_linux_gtk_x86/configuration/org.eclipse.osgi/289/0/.cp/icons/etool16/alphab_sort_co.gif
/home/bhaskar/.eclipse/org.eclipse.platform_155965261_linux_gtk_x86/configuration/org.eclipse.osgi/300/0/.cp/icons/dlcl16/alphab_sort_co.gif
/home/bhaskar/.eclipse/org.eclipse.platform_155965261_linux_gtk_x86/configuration/org.eclipse.osgi/300/0/.cp/icons/elcl16/alphab_sort_co.gif
/home/bhaskar/Downloads/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/balanced_quicksort.h
/home/bhaskar/Downloads/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/multiway_mergesort.h
/home/bhaskar/Downloads/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/quicksort.h
/home/bhaskar/Downloads/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/sort.h
/home/bhaskar/opt/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/balanced_quicksort.h
/home/bhaskar/opt/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/multiway_mergesort.h
/home/bhaskar/opt/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/quicksort.h
/home/bhaskar/opt/gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1-20180724-0637/arm-none-eabi/include/c++/7.3.1/parallel/sort.h
/usr/avr/share/man/man3/qsort.3.gz
/usr/bin/rpmdev-sort
/usr/bin/sort
/usr/bin/tsort
/usr/include/c++/8/parallel/balanced_quicksort.h
/usr/include/c++/8/parallel/multiway_mergesort.h
/usr/include/c++/8/parallel/quicksort.h
/usr/include/c++/8/parallel/sort.h
/usr/include/qt5/QtCore/qsortfilterproxymodel.h
/usr/lib/eclipse/plugins/org.apache.ant_1.10.5.v20180808-0324/etc/checkstyle/checkstyle-frames-sortby-check.xsl
/usr/lib/guile/2.0/ccache/rnrs/sorting.go
/usr/lib/ldb/modules/ldb/server_sort.so
/usr/lib/libkkc/models/sorted3
/usr/lib/libkkc/models/sorted3/data.1gram
/usr/lib/libkkc/models/sorted3/data.1gram.index
/usr/lib/libkkc/models/sorted3/data.2gram
/usr/lib/libkkc/models/sorted3/data.2gram.filter
/usr/lib/libkkc/models/sorted3/data.3gram
/usr/lib/libkkc/models/sorted3/data.3gram.filter
/usr/lib/libkkc/models/sorted3/data.input
/usr/lib/libkkc/models/sorted3/metadata.json
/usr/lib/python3.7/site-packages/blivet/tsort.py
/usr/lib/python3.7/site-packages/blivet/__pycache__/tsort.cpython-37.opt-1.pyc
/usr/lib/python3.7/site-packages/blivet/__pycache__/tsort.cpython-37.pyc
/usr/lib/python3.7/site-packages/coverage/htmlfiles/jquery.tablesorter.min.js
/usr/lib/systemd/system/mdadm-last-resort@.service
/usr/lib/systemd/system/mdadm-last-resort@.timer
/usr/sbin/grub2-rpm-sort
/usr/share/awk/quicksort.awk
/usr/share/doc/rpm/tsort
/usr/share/glade/pixmaps/hicolor/16x16/actions/widget-gtk-treemodelsort.png
/usr/share/glade/pixmaps/hicolor/22x22/actions/widget-gtk-treemodelsort.png
/usr/share/guile/2.0/rnrs/sorting.scm
/usr/share/help/C/gnumeric/figures/button-sort-az.png
/usr/share/help/C/gnumeric/figures/button-sort-za.png
/usr/share/help/C/gnumeric/figures/preferences-sorting.png
/usr/share/help/cs/gnumeric/figures/button-sort-az.png
/usr/share/help/cs/gnumeric/figures/button-sort-za.png
/usr/share/help/cs/gnumeric/figures/preferences-sorting.png
/usr/share/help/de/gnumeric/figures/button-sort-az.png
/usr/share/help/de/gnumeric/figures/button-sort-za.png
/usr/share/help/de/gnumeric/figures/preferences-sorting.png
/usr/share/help/es/gnumeric/figures/button-sort-az.png
/usr/share/help/es/gnumeric/figures/button-sort-za.png
/usr/share/help/es/gnumeric/figures/preferences-sorting.png
/usr/share/icons/Adwaita/16x16/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/actions/view-sort-ascending.png
/usr/share/icons/Adwaita/16x16/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/actions/view-sort-descending.png
/usr/share/icons/Adwaita/22x22/actions/view-sort-ascending.png
/usr/share/icons/Adwaita/22x22/actions/view-sort-descending.png
/usr/share/icons/Adwaita/24x24/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/view-sort-ascending.png
/usr/share/icons/Adwaita/24x24/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/view-sort-descending.png
/usr/share/icons/Adwaita/32x32/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/view-sort-ascending.png
/usr/share/icons/Adwaita/32x32/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/view-sort-descending.png
/usr/share/icons/Adwaita/48x48/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/view-sort-ascending.png
/usr/share/icons/Adwaita/48x48/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/view-sort-descending.png
/usr/share/icons/Adwaita/64x64/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/64x64/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/view-sort-ascending-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/view-sort-descending-symbolic.symbolic.png
/usr/share/icons/Adwaita/scalable/actions/view-sort-ascending-symbolic.svg
/usr/share/icons/Adwaita/scalable/actions/view-sort-descending-symbolic.svg
/usr/share/icons/HighContrast/16x16/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/16x16/actions/view-sort-descending.png
/usr/share/icons/HighContrast/22x22/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/22x22/actions/view-sort-descending.png
/usr/share/icons/HighContrast/24x24/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/24x24/actions/view-sort-descending.png
/usr/share/icons/HighContrast/256x256/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/256x256/actions/view-sort-descending.png
/usr/share/icons/HighContrast/32x32/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/32x32/actions/view-sort-descending.png
/usr/share/icons/HighContrast/48x48/actions/view-sort-ascending.png
/usr/share/icons/HighContrast/48x48/actions/view-sort-descending.png
/usr/share/icons/HighContrast/scalable/actions/view-sort-ascending.svg
/usr/share/icons/HighContrast/scalable/actions/view-sort-descending.svg
/usr/share/icons/gnome/16x16/actions/view-sort-ascending.png
/usr/share/icons/gnome/16x16/actions/view-sort-descending.png
/usr/share/icons/gnome/22x22/actions/view-sort-ascending.png
/usr/share/icons/gnome/22x22/actions/view-sort-descending.png
/usr/share/icons/gnome/24x24/actions/view-sort-ascending.png
/usr/share/icons/gnome/24x24/actions/view-sort-descending.png
/usr/share/icons/gnome/32x32/actions/view-sort-ascending.png
/usr/share/icons/gnome/32x32/actions/view-sort-descending.png
/usr/share/icons/gnome/48x48/actions/view-sort-ascending.png
/usr/share/icons/gnome/48x48/actions/view-sort-descending.png
/usr/share/libkkc/templates/libkkc-data/data/models/Makefile.sorted2
/usr/share/libkkc/templates/libkkc-data/data/models/Makefile.sorted3
/usr/share/libkkc/templates/libkkc-data/data/models/sorted2
/usr/share/libkkc/templates/libkkc-data/data/models/sorted3
/usr/share/libkkc/templates/libkkc-data/data/models/sorted2/metadata.json
/usr/share/libkkc/templates/libkkc-data/data/models/sorted3/metadata.json
/usr/share/libkkc/templates/libkkc-data/tools/sortlm.py
/usr/share/man/man1/sort.1.gz
/usr/share/man/man1/tsort.1.gz
/usr/share/man/man1p/sort.1p.gz
/usr/share/man/man1p/tsort.1p.gz
/usr/share/man/man3/alphasort.3.gz
/usr/share/man/man3/qsort.3.gz
/usr/share/man/man3/qsort_r.3.gz
/usr/share/man/man3/sort.3pm.gz
/usr/share/man/man3/versionsort.3.gz
/usr/share/man/man3p/alphasort.3p.gz
/usr/share/man/man3p/qsort.3p.gz
/usr/share/man/man8/grub2-rpm-sort.8.gz
/usr/share/perl5/sort.pm
/usr/share/pingus/images/exits/sortie.png
/usr/share/pingus/images/exits/sortie.sprite
/usr/share/pingus/images/exits/sortie_anim.png
/usr/share/pingus/images/exits/sortie_anim.sprite
/usr/share/pingus/images/groundpieces/ground/sortie
/usr/share/pingus/images/groundpieces/ground/sortie/ball1.png
/usr/share/pingus/images/groundpieces/ground/sortie/ball2.png
/usr/share/pingus/images/groundpieces/ground/sortie/ball3.png
/usr/share/pingus/images/groundpieces/ground/sortie/ball4.png
/usr/share/pingus/images/groundpieces/ground/sortie/column.png
/usr/share/pingus/images/groundpieces/ground/sortie/column2.png
/usr/share/pingus/images/groundpieces/ground/sortie/column3.png
/usr/share/pingus/images/groundpieces/ground/sortie/plate_forme.png
/usr/share/pingus/images/groundpieces/ground/sortie/plate_forme_left.png
/usr/share/pingus/images/groundpieces/ground/sortie/plate_forme_right.png
/usr/share/pingus/images/groundpieces/ground/sortie/tentacle1.png
/usr/share/pingus/images/groundpieces/ground/sweets/allsort1.png
/usr/share/pingus/images/groundpieces/ground/sweets/allsort2.png
/usr/share/pingus/images/prefabs/sortie_entrance.png
/usr/share/pingus/images/prefabs/sortie_entrance.sprite
/usr/share/pingus/images/prefabs/entrances/sortie.png
/usr/share/pingus/images/prefabs/entrances/sortie.sprite
/usr/share/pingus/images/textures/bwsortiebg.jpg
/usr/share/pingus/images/textures/sortie.jpg
/usr/share/pingus/images/textures/sortiebgred.jpg
/usr/share/pingus/levels/playable/sortie1.pingus
/usr/share/pingus/levels/wip/sortie-lukis.pingus
/usr/share/pingus/levels/wip/sortie2.pingus
/usr/share/pingus/levels/wip/sortie3.pingus
/usr/share/pingus/levels/xskat/ok/sortie4-grumbel.pingus
/usr/share/pingus/prefabs/entrances/sortie.prefab
/usr/share/yelp-xsl/xslt/mallard/common/mal-sort.xsl
/usr/src/kernels/4.19.10-300.fc29.i686/include/config/buildtime/extable/sort.h
/usr/src/kernels/4.19.10-300.fc29.i686/include/linux/list_sort.h
/usr/src/kernels/4.19.10-300.fc29.i686/include/linux/sort.h
/usr/src/kernels/4.19.10-300.fc29.i686/scripts/sortextable
/usr/src/kernels/4.19.10-300.fc29.i686/scripts/sortextable.c
/usr/src/kernels/4.19.10-300.fc29.i686/scripts/sortextable.h
