msgserver3: msgserver3.o
	gcc -o msgserver3 msgserver3.o

msgserver3.o: msgserver3.c
	gcc -o msgserver3.o -c msgserver3.c

msgclient3: msgclient3.o
	gcc -o msgclient3 msgclient3.o

msgclient3.o: msgclient3.c
	gcc -o msgclient3.o -c msgclient3.c

clean:
	rm *.o
